Settings = {
	'faps': ["seisatsu.png"
		,"seisatsu.avi"
		,"Boxxy"
		,"Abasiophilia - People with impaired mobility"
		,"Autoerotic asphixiation - Self-induced asphyxiation, sometimes to the point of near unconsciousness"
		,"Erotic asphyxiation - Asphyxia of oneself or others"
		,"Telephone scatologia - Obscene phone calls, particularly to strangers"
		,"Transvestic fetishism - Cross-dressing / Wearing clothes associated with the opposite sex"
		,"Chremastistophilia - Being robbed or held up"
		,"Splanchnophilia - Entrails"
		,"Hebephilia - Generally early pubescent children"
		,"Sacofricosis - Making a hole in a pocket in order to masturbate unobtrusively in public"
		,"Infantophilia - Pedophilia with a focus on children five years old or younger"
		,"Nasophilia - Noses"
		,"Autassassinophilia - Being in life-threatening situations"
		,"Crush - fetish Squashing of animals, food, or other objects"
		,"Autogynephilia - A biological male imagining himself as a female"
		,"Symphorophilia - Witnessing or staging disasters such as car accidents"
		,"Anililagnia - Attraction by young men to older women"
		,"Stigmatophilia - Body piercings and tattoos"
		,"Salirophilia - Soiling or dirtying others"
		,"Mammaphilia/Breast - fetishism Breasts; also known as mammagynophilia and mastofact"
		,"Autoandrophilia - A biological female imagining herself as a male"
		,"Olfactophilia - Smells"
		,"Formicophilia - Being crawled on by insects"
		,"Narratophilia - Dirty talk Obscene words"
		,"Pedovestism - Dressing like a child"
		,"Mechanophilia - Cars or other machines; also 'mechaphilia'"
		,"Piquerism - Sexual gratification through penetration of another person, most commonly by stabbing or cutting the body with sharp objects"
		,"Exhibitionism - Exposing oneself sexually to others, with or without their consent"
		,"Emetophilia - Vomit"
		,"Mysophilia - Dirtiness, soiled or decaying things"
		,"Pictophilia - Pornography or erotic art, particularly pictures"
		,"Sthenolagnia - Muscle worship Muscles and displays of strength"
		,"Mucophilia - Mucus"
		,"Somnophilia - Sleeping or unconscious people"
		,"Andromimetophilia - Trans men"
		,"Klismaphilia - Enemas"
		,"Masochism - BDSM Suffering; being beaten, bound or otherwise humiliated"
		,"Hybristophilia - Criminals, particularly for cruel or outrageous crimes"
		,"Paraphilic - infantilism Adult baby/Diaper lover (AB/DL) / 'adult baby syndrome'"
		,"Homeovestism - Wearing clothing emblematic of one's own sex"
		,"Pedophilia - Prepubescent children, also spelled paedophilia. Often confused with hebephilia, ephebophilia, and pederasty"
		,"Podophilia - Foot fetish/Feet"
		,"Acrotomophilia - Amputee fetish People with amputations"
		,"Liquidophilia - Immersing genitals in liquids"
		,"Navel - fetishism Belly button fetish Sexual attraction to navels - either their own or someone else's"
		,"Sadism - BDSM Inflicting pain on others"
		,"Asphyxiophilia - Asphyxiation or strangulation"
		,"Biastophilia - Rape of an unconsenting person; see also consensual rape fantasy"
		,"Gynemimetophilia - Transwomen Transsexual or transgender women"
		,"Teratophilia - Deformed or monstrous people"
		,"Morphophilia - Particular body shapes or sizes"
		,"Autagonistophilia - Being on stage or on camera"
		,"Forniphilia - Human furniture Turning a human being into a piece of furniture"
		,"Gerontophilia - Elderly people"
		,"Macrophilia - Giants, primarily domination by giant women or men"
		,"Kleptophilia - Stealing; also known as kleptolagnia"
		,"Coprophilia - Scat Feces; also known as scat, scatophilia or fecophilia"
		,"Frotteurism - Rubbing against a non-consenting person"
		,"Chronophilia - Partners of a widely differing chronological age"
		,"Raptophilia - Committing rape, possibly consensual rape fantasy"
		,"Agalmatophilia - Statues, mannequins and immobility"
		,"Peodeiktophilia - Exposing one's penis"
		,"Dacryphilia - Tears or crying"
		,"Apotemnophilia - Having an amputation"
		,"Algolagnia - Pain, particularly involving an erogenous zone"
		,"Lactophilia - Breast milk"
		,"Pyrophilia - Fire"
		,"Pygophilia - Buttocks"
		,"Erotophonophilia - Murder"
		,"Necrophilia - Corpses"
		,"Menophilia - Menstruation"
		,"Partialism - Specific, non-genital body parts"
		,"Dendrophilia - Trees"
		,"Transvestophilia - A transvestite sexual partner"
		,"Trichophilia - Hair"
		,"Troilism - Cuckolding / Cuckoldism"
		,"Urolagnia - Piss play / Urination, particularly in public, on others, and/or being urinated on"
		,"Vampirism - Blood play / Attraction to or involving blood"
		,"Vorarephilia - Vore / The idea of eating or being eaten by others; usually swallowed whole, in one piece"
		,"Voyeurism - Watching others while naked or having sex, generally without their knowledge"
		,"Zoophilia - Animals"
		,"Zoosadism - Bestiality / inflicting pain on or seeing animals in pain"
		,"Boku No Pico"
		,"Ponies"
		,"Cleavage"
		,"Ass"
		,"Buttplugs"
		,"Lesbians"
		,"raldakejla"
		,"Vanilla heterosexual porn with no kinky shit whatsoever!"
		,"Gay porn. Also, {nick} is now gay!"
		,"Foot fetishism – Sexual interest in feet!"
		,"Bodacious booties – No explanation needed!"
		,"Oral sex – Stimulation of the genitalia by the mouth!"
		,"Anal sex – Penetration of the anus with a penis or phallic object!"
		,"Internal cumshots – The act of ejaculating into a bodily orifice"
		,"Swimwear – People in bathing suits!"
		,"Celebrities – leaked explicit videos and photographs of famous individuals!"
		,"Voyeurism – The witnessing of a sex act with out the permission of the participants!"
		,"Exhibitionism – The display of nudity or sexuality to an audience, willing or not!"
		,"Interracial – The sexual pairing of two partners of different ethnic backgrounds!"
		,"Asians – People of East Asian decent!"
		,"Sadism – Inflicting pain on a submissive partner!"
		,"Masochism – Receiving pain from a dominant partner!"
		,"Bondage – the use of physical restraints on one sexual partner by the other!"
		,"Pegging – The penetration of a male by a female with an artificial phallus!"
		,"Non-penetrative intercourse – sexual stimulation not involving the penis in a bodily orifice!"
		,"Group sex – sexual interaction between a group of three or more people!"
		,"Bukkake – The ejaculation of multiple males onto a single individual!"
		,"Haemotolangia – Sexual interest in blood and bleeding!"
		,"Yaoi – Hentai centered around a homosexual male couple!"
		,"Yuri – Hentai centered around a homosexual female couple!"
		,"Transformations – The physical change of a person, often to a different age or sex!"
		,"Tentacle porn – Sexual interaction between a human and some tentacled creature!"
		,"Traps – Girls with male genitalia!"
		,"Futa – Girls with both male and female genitalia!"
		,"Anthromorphism – Humanoid figures with animal qualities, especially fur!"
		,"Incest – Sexual interaction between blood relatives!"
		,"Pregnant women!"
		,"80s porn – Mustaches and untrimmed bush set to epic guitar solos!"
		,"Vintage pornography – What our grandparents fapped to!"
		,"Gigantism – People of unnaturally large size, especially interacting with normal sized people!"
		,"Fursuiting – Preforming sex acts through specially cut holes in full body animal suits!"
		,"Inflation – the often unrealistic expansion of the body!"
		,"Genital mutilation – permanent disfigurement of the genital area!"
		,"Vorarephilia – the consumption of a living being by another, often whole and alive!"
		,"Cock vorarephilia – oh my god what the fuck this actually exists and {nick} has to fap to it!"
		,"Autonepiophilia – roleplaying of adults as babies, often with emphasis on diapers!"
		,"Sonic the Hegehog fan fiction!"
		,"Chris-chan's JULAAAAAAY.avi!"
		,"the first person found on chat roulette or omegle!"
		,"anything linked from the hidden wiki's paraphilia section!"
		,"Cybering with cleverbot!"
		,"My Little Pony porn!"
		,"the Holocaust!"
		,"Nothing. {nick} has to go to bed!"
		,"Seisatsu.png!"
		,"Chemfag's nudes!"
		,"Phantasm's face!"
		,"Bad Hunter rape fantasy!"
		,"Alchazar's limp dick!"
		,"Anonynom's underaged chest!"
		,"Marina's man boobs!"
		,"the asshole on the frtongpage!"
	]
}
